global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-api'
    static_configs:
      - targets: ['node-api:3000']
    metrics_path: /metrics

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']